package com.bigbincom.bigbin.entity;

import java.util.Date;

public class BZUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_z_user.xlh
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    private String xlh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_z_user.username
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_z_user.password
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_z_user.ip
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_z_user.email
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_z_user.zcsj
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    private Date zcsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_z_user.phone
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_z_user.photo
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_z_user.yhqx
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    private String yhqx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_z_user.xlh
     *
     * @return the value of b_z_user.xlh
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public String getXlh() {
        return xlh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_z_user.xlh
     *
     * @param xlh the value for b_z_user.xlh
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public void setXlh(String xlh) {
        this.xlh = xlh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_z_user.username
     *
     * @return the value of b_z_user.username
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_z_user.username
     *
     * @param username the value for b_z_user.username
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_z_user.password
     *
     * @return the value of b_z_user.password
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_z_user.password
     *
     * @param password the value for b_z_user.password
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_z_user.ip
     *
     * @return the value of b_z_user.ip
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_z_user.ip
     *
     * @param ip the value for b_z_user.ip
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_z_user.email
     *
     * @return the value of b_z_user.email
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_z_user.email
     *
     * @param email the value for b_z_user.email
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_z_user.zcsj
     *
     * @return the value of b_z_user.zcsj
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public Date getZcsj() {
        return zcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_z_user.zcsj
     *
     * @param zcsj the value for b_z_user.zcsj
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public void setZcsj(Date zcsj) {
        this.zcsj = zcsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_z_user.phone
     *
     * @return the value of b_z_user.phone
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_z_user.phone
     *
     * @param phone the value for b_z_user.phone
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_z_user.photo
     *
     * @return the value of b_z_user.photo
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_z_user.photo
     *
     * @param photo the value for b_z_user.photo
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_z_user.yhqx
     *
     * @return the value of b_z_user.yhqx
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public String getYhqx() {
        return yhqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_z_user.yhqx
     *
     * @param yhqx the value for b_z_user.yhqx
     *
     * @mbg.generated Tue Jan 19 10:39:20 CST 2021
     */
    public void setYhqx(String yhqx) {
        this.yhqx = yhqx;
    }
}